/********************************************************************
* dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevdict();
extern G__DLLEXPORT void G__set_cpp_environmentdict();
extern G__DLLEXPORT void G__cpp_setup_tagtabledict();
extern G__DLLEXPORT void G__cpp_setup_inheritancedict();
extern G__DLLEXPORT void G__cpp_setup_typetabledict();
extern G__DLLEXPORT void G__cpp_setup_memvardict();
extern G__DLLEXPORT void G__cpp_setup_globaldict();
extern G__DLLEXPORT void G__cpp_setup_memfuncdict();
extern G__DLLEXPORT void G__cpp_setup_funcdict();
extern G__DLLEXPORT void G__cpp_setupdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DataSet.h"
#include "Group.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__dictLN_Hit;
extern G__linked_taginfo G__dictLN_Particle;
extern G__linked_taginfo G__dictLN_vectorlEHitcOallocatorlEHitgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEHitcOallocatorlEHitgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_iteratorlErandom_access_iterator_tagcOHitcOlongcOHitmUcOHitaNgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEHitcOallocatorlEHitgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__dictLN_Group;
extern G__linked_taginfo G__dictLN_vectorlESetcOallocatorlESetgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlESetcOallocatorlESetgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_iteratorlErandom_access_iterator_tagcOSetcOlongcOSetmUcOSetaNgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlESetcOallocatorlESetgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__dictLN_DataSet;
extern G__linked_taginfo G__dictLN_vectorlEGroupmUcOallocatorlEGroupmUgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEGroupmUcOallocatorlEGroupmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_iteratorlErandom_access_iterator_tagcOGroupmUcOlongcOGroupmUmUcOGroupmUaNgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEGroupmUcOallocatorlEGroupmUgRsPgRcLcLconst_iteratorgR;

/* STUB derived class for protected member access */
